package embed

// Landmarks are fixed "anchor" feature sets that define the semantic basis
// for our coordinate system. They represent stable concepts that do not
// change, even if the underlying model logic is updated.
//
// These strings are used to generate a "reference vector" for each landmark.
// A final text embedding is the similarity profile of the input text
// relative to these landmarks.
var landmarkBasis = []string{
	// ── ABSTRACT & STRUCTURAL (0–15) ────────────────────────────────────────
	"logic, reason, mathematical proof, formal system",
	"chaos, randomness, entropy, noise",
	"structure, organization, hierarchy, architecture",
	"pattern, symmetry, repetition, rhythm",
	"change, transformation, transition, evolution",
	"stability, permanence, constant, fixed",
	"complexity, intricate, elaborate, detailed",
	"simplicity, basic, plain, essential",
	"quality, excellence, standard, value",
	"quantity, amount, number, measure",
	"possibility, potential, maybe, could",
	"certainty, absolute, fact, truth",
	"unity, whole, together, integrated",
	"diversity, variety, different, multiple",
	"balance, equilibrium, parity, steady",
	"conflict, tension, friction, opposition",

	// ── TECHNOLOGY & COMPUTING (16–25) ──────────────────────────────────────
	"software, computer, code, algorithm, digital",
	"hardware, circuit, machine, engine, tool",
	"internet, network, web, cloud, online",
	"data, information, database, storage",
	"security, encryption, firewall, protection",
	"automation, robot, intelligence, autonomous",
	"interface, screen, user, interaction",
	"mobile, wireless, phone, cellular",
	"virtual, augmented, reality, simulation",
	"programming, developer, syntax, compile",

	// ── SCIENCE & MATHEMATICS (26–38) ───────────────────────────────────────
	"physics, matter, energy, quantum, space",
	"chemistry, molecule, reaction, element, lab",
	"biology, life, organism, evolution, genetic",
	"astronomy, star, planet, galaxy, universe",
	"geology, earth, rock, mineral, tectonic",
	"ecology, environment, nature, system",
	"mathematics, number, calculus, geometry",
	"statistics, probability, data, average",
	"engineering, design, build, construct",
	"research, experiment, hypothesis, theory",
	"psychology, mind, behavior, mental",
	"sociology, society, group, culture",
	"economics, market, wealth, trade",

	// ── SOCIAL & HUMAN (39–51) ──────────────────────────────────────────────
	"finance, money, economy, market, trade",
	"justice, law, ethics, right, wrong",
	"politics, government, power, state, citizen",
	"education, school, learning, teacher, student",
	"religion, spirit, soul, faith, divine",
	"philosophy, thought, idea, wisdom, mind",
	"history, past, ancient, era, century",
	"family, parent, child, relative, home",
	"community, neighborhood, city, local",
	"health, wellness, fitness, body",
	"medicine, doctor, hospital, treatment",
	"sports, game, athletic, team, competition",
	"fashion, style, clothing, appearance",

	// ── ARTS & CULTURE (52–62) ──────────────────────────────────────────────
	"art, beauty, creativity, aesthetic, expression",
	"music, sound, rhythm, melody, instrument",
	"literature, book, writing, story, poetry",
	"film, movie, cinema, screen, director",
	"theater, stage, performance, actor",
	"photography, image, camera, light, frame",
	"dance, movement, choreography, body",
	"design, graphic, layout, visual",
	"architecture, building, space, urban",
	"media, news, journalism, broadcast",
	"culinary, food, cooking, chef, taste",

	// ── NATURE & ENVIRONMENT (63–72) ────────────────────────────────────────
	"weather, climate, rain, sun, storm",
	"animal, mammal, bird, fish, insect",
	"plant, flower, tree, leaf, forest",
	"ocean, sea, water, coast, marine",
	"mountain, hill, peak, valley, land",
	"desert, sand, dry, heat, arid",
	"arctic, ice, snow, cold, frozen",
	"space, celestial, void, vacuum",
	"atmosphere, air, wind, oxygen",
	"energy, power, fuel, renewable, solar",

	// ── EMOTIONS & QUALITIES (73–84) ────────────────────────────────────────
	"love, affection, care, passion",
	"fear, anxiety, terror, dread",
	"joy, happiness, delight, bliss",
	"sadness, grief, sorrow, misery",
	"anger, rage, fury, wrath",
	"surprise, wonder, amazement, shock",
	"trust, faith, belief, confidence",
	"courage, brave, bold, valor",
	"wisdom, smart, intelligent, clever",
	"patience, calm, steady, endure",
	"honest, true, sincere, candid",
	"kindness, gentle, soft, warm",

	// ── TIME & MOTION (85–94) ────────────────────────────────────────────────
	"past, history, memory, ancient",
	"future, tomorrow, vision, goal",
	"present, now, current, instant",
	"speed, fast, rapid, quick, velocity",
	"slow, gradual, delay, crawl",
	"motion, movement, flow, dynamic",
	"time, clock, hour, minute, second",
	"begin, start, origin, birth",
	"end, finish, death, conclude",
	"frequency, often, rare, repeat",

	// ── PHYSICAL PROPERTIES (95–102) ────────────────────────────────────────
	"size, big, large, huge, massive",
	"small, tiny, micro, minute",
	"weight, heavy, light, mass",
	"texture, rough, smooth, hard, soft",
	"color, bright, dark, vivid, pale",
	"shape, round, square, sharp, flat",
	"temperature, hot, cold, warm, cool",
	"distance, far, near, close, away",

	// ── PROGRAMMING LANGUAGES (103–122) ─────────────────────────────────────
	"python, scripting, interpreted, dynamic, indentation",
	"javascript, typescript, nodejs, browser, event, loop",
	"java, jvm, object, oriented, enterprise, spring",
	"golang, goroutine, channel, concurrency, compiled",
	"rust, memory, safe, ownership, borrow, checker",
	"c, cpp, pointer, low, level, system, unsafe",
	"swift, ios, apple, macos, optional, protocol",
	"kotlin, android, coroutine, null, safe, modern",
	"ruby, rails, gem, metaprogramming, dynamic, web",
	"php, web, server, laravel, composer, dynamic",
	"scala, functional, jvm, spark, type, inference",
	"haskell, purely, functional, monadic, lazy, evaluation",
	"shell, bash, script, command, unix, posix",
	"sql, query, relational, select, join, table",
	"r, statistical, analysis, data, visualization, ggplot",
	"matlab, numerical, matrix, simulation, scientific",
	"assembly, machine, instruction, register, opcode",
	"lisp, scheme, macro, expression, homoiconic",
	"dart, flutter, cross, platform, reactive, widget",
	"elixir, erlang, concurrent, fault, tolerant, otp",

	// ── SOFTWARE PARADIGMS & PATTERNS (123–142) ──────────────────────────────
	"object, oriented, class, inheritance, polymorphism, encapsulation",
	"functional, pure, immutable, map, reduce, compose, higher, order",
	"reactive, event, driven, stream, observable, backpressure",
	"declarative, describe, what, not, how, constraint",
	"imperative, step, command, sequential, control, flow",
	"design, pattern, factory, singleton, observer, decorator",
	"microservice, service, independent, deploy, api, boundary",
	"monolithic, single, application, coupled, deploy, module",
	"model, view, controller, mvc, separation, concern",
	"repository, pattern, data, access, layer, abstraction",
	"dependency, injection, inversion, control, ioc, container",
	"event, sourcing, command, cqrs, message, immutable",
	"domain, driven, design, aggregate, bounded, context",
	"layered, architecture, tier, presentation, business, logic",
	"pipeline, stage, filter, transform, compose, step",
	"state, machine, finite, transition, automaton, event",
	"middleware, intercept, request, chain, hook, plug",
	"plugin, extension, module, dynamic, load, hook",
	"observer, publish, subscribe, listener, notify, decouple",
	"strategy, algorithm, replace, interchangeable, policy, pattern",

	// ── DATA STRUCTURES (143–157) ────────────────────────────────────────────
	"array, list, sequence, index, element, contiguous",
	"linked, list, node, pointer, traverse, singly, doubly",
	"tree, binary, node, leaf, branch, depth, height",
	"graph, vertex, edge, directed, weighted, adjacency",
	"hash, map, dictionary, key, value, lookup, bucket",
	"heap, priority, queue, max, min, tree, extract",
	"stack, push, pop, lifo, call, frame, overflow",
	"queue, fifo, enqueue, dequeue, buffer, circular",
	"set, unique, membership, union, intersection, difference",
	"trie, prefix, string, search, autocomplete, compress",
	"matrix, grid, two, dimension, row, column, element",
	"bloom, filter, probabilistic, membership, false, positive",
	"ring, buffer, circular, capacity, overflow, wrap",
	"cache, lru, evict, miss, hit, store, locality",
	"bitset, bit, flag, mask, operation, compact",

	// ── ALGORITHMS & COMPLEXITY (158–172) ────────────────────────────────────
	"sort, order, comparison, merge, quick, heap, stable",
	"search, binary, linear, find, locate, divide",
	"recursion, base, case, call, stack, depth, inductive",
	"dynamic, programming, memoize, subproblem, tabulate, optimal",
	"greedy, local, optimal, heuristic, approximate, choice",
	"divide, conquer, split, merge, recursive, subproblem",
	"backtrack, explore, prune, constraint, satisfy, depth",
	"graph, traversal, bfs, dfs, shortest, path, dijkstra",
	"string, match, pattern, regex, kmp, suffix, array",
	"compression, huffman, entropy, encode, decode, lz",
	"hash, collision, load, factor, open, address, chain",
	"complexity, big, o, time, space, bound, asymptotic",
	"parallel, concurrent, thread, lock, synchronize, fork",
	"approximation, randomized, monte, carlo, sample, probabilistic",
	"streaming, online, incremental, batch, window, sliding",

	// ── DATABASES & STORAGE (173–192) ────────────────────────────────────────
	"relational, table, row, column, schema, constraint",
	"nosql, document, flexible, schema, schemaless, store",
	"key, value, redis, store, cache, memory, ttl",
	"document, mongodb, json, collection, index, bson",
	"graph, database, neo4j, relationship, traverse, cypher",
	"column, family, cassandra, wide, bigtable, partition",
	"time, series, influx, metric, timestamp, retention",
	"transaction, acid, commit, rollback, isolation, durability",
	"index, btree, scan, query, performance, covering",
	"join, inner, outer, left, right, cross, merge",
	"aggregate, group, count, sum, average, window, function",
	"migration, schema, change, version, upgrade, flyway",
	"replication, primary, replica, sync, consistency, lag",
	"sharding, partition, distribute, shard, horizontal, scale",
	"backup, restore, snapshot, recovery, point, time",
	"orm, object, relational, mapping, model, entity",
	"query, optimize, plan, execution, cost, index, hint",
	"vector, embedding, similarity, search, qdrant, approximate",
	"object, storage, s3, blob, bucket, file, immutable",
	"distributed, lock, consensus, etcd, zookeeper, lease",

	// ── NETWORKING & PROTOCOLS (193–212) ─────────────────────────────────────
	"http, request, response, header, status, method, rest",
	"tcp, connection, socket, reliable, stream, handshake",
	"udp, datagram, packet, fast, connectionless, broadcast",
	"dns, domain, resolve, host, lookup, nameserver",
	"tls, ssl, certificate, encrypt, handshake, verify",
	"websocket, realtime, bidirectional, connection, push, upgrade",
	"grpc, protobuf, service, call, stream, deadline",
	"graphql, query, mutation, resolver, schema, type",
	"mqtt, iot, broker, publish, subscribe, topic, qos",
	"load, balancer, round, robin, health, check, sticky",
	"proxy, reverse, forward, gateway, traffic, sni",
	"cdn, edge, cache, distribute, content, origin, pop",
	"firewall, rule, policy, block, allow, filter, ingress",
	"vpn, tunnel, encrypted, private, network, wireguard",
	"ip, address, subnet, cidr, routing, bgp, ospf",
	"nat, translation, masquerade, address, port, map",
	"http2, http3, quic, multiplexed, stream, push",
	"oauth, openid, jwt, token, bearer, scope, claim",
	"webhook, callback, event, push, notification, retry",
	"rate, limit, throttle, backpressure, quota, token, bucket",

	// ── CLOUD & INFRASTRUCTURE (213–232) ─────────────────────────────────────
	"aws, amazon, cloud, service, ec2, lambda, s3",
	"azure, microsoft, cloud, resource, group, arm",
	"gcp, google, cloud, kubernetes, bigquery, pubsub",
	"kubernetes, container, orchestrate, pod, deploy, helm",
	"docker, container, image, layer, registry, compose",
	"serverless, lambda, function, trigger, cold, start",
	"terraform, infrastructure, code, provision, resource, plan",
	"ansible, playbook, automate, configure, role, idempotent",
	"helm, chart, kubernetes, package, release, values",
	"service, mesh, istio, linkerd, sidecar, envoy",
	"observability, trace, metric, log, signal, telemetry",
	"chaos, engineering, fault, inject, resilience, gameday",
	"autoscale, horizontal, vertical, scale, load, demand",
	"region, zone, availability, redundancy, fault, tolerance",
	"iam, role, permission, policy, access, cloud, principal",
	"managed, service, database, cache, queue, serverless",
	"cost, billing, budget, resource, optimize, rightsizing",
	"multi, cloud, hybrid, workload, portability, vendor",
	"edge, computing, local, process, latency, iot, fog",
	"secrets, vault, rotate, kms, encrypt, store, hsm",

	// ── DEVOPS & DEPLOYMENT (233–247) ────────────────────────────────────────
	"ci, cd, pipeline, build, test, deploy, automate",
	"git, branch, merge, pull, request, commit, history",
	"version, release, semver, tag, changelog, bump",
	"blue, green, deployment, canary, rollout, traffic",
	"feature, flag, toggle, experiment, gradual, rollout",
	"monitoring, alert, dashboard, metric, grafana, slo",
	"logging, log, aggregation, elk, splunk, structured",
	"tracing, span, distributed, opentelemetry, jaeger, zipkin",
	"incident, postmortem, sre, reliability, uptime, blameless",
	"artifact, registry, publish, package, npm, pypi",
	"environment, staging, production, develop, config, promote",
	"rollback, revert, deploy, previous, version, restore",
	"health, check, readiness, liveness, probe, startup",
	"configuration, management, drift, baseline, state, ansible",
	"infrastructure, immutable, bake, ami, image, replace",

	// ── TESTING & QUALITY (248–262) ──────────────────────────────────────────
	"unit, test, mock, assert, isolate, fixture, small",
	"integration, test, service, real, database, compose",
	"end, to, end, test, browser, playwright, user, flow",
	"property, based, test, fuzz, generate, input, shrink",
	"test, coverage, line, branch, mutation, threshold",
	"benchmark, performance, load, stress, latency, k6",
	"regression, test, prevent, fix, reintroduce, suite",
	"snapshot, test, ui, component, render, approve",
	"contract, test, api, pact, consumer, provider",
	"static, analysis, lint, type, check, sonar, smell",
	"code, review, feedback, quality, standard, pair",
	"bug, defect, reproduce, fix, report, triage",
	"test, driven, development, tdd, red, green, refactor",
	"acceptance, criteria, user, story, requirement, scenario",
	"flaky, test, intermittent, unstable, retry, quarantine",

	// ── APIS & INTEGRATION (263–277) ─────────────────────────────────────────
	"rest, api, endpoint, resource, crud, stateless",
	"soap, xml, wsdl, enterprise, legacy, envelope",
	"webhook, event, payload, secret, verify, hmac",
	"api, key, authentication, header, token, revoke",
	"rate, limit, quota, retry, exponential, backoff, jitter",
	"pagination, cursor, page, offset, limit, total",
	"versioning, breaking, change, deprecate, sunset, migrate",
	"sdk, client, library, wrapper, integration, binding",
	"openapi, swagger, specification, document, generate, mock",
	"idempotent, safe, method, retry, duplicate, key",
	"batch, bulk, operation, request, efficiency, parallel",
	"streaming, server, sent, event, chunk, chunked",
	"serialization, json, xml, protobuf, avro, thrift",
	"transform, map, convert, schema, format, adapt",
	"mock, stub, fake, server, test, api, record",

	// ── MACHINE LEARNING & AI (278–297) ──────────────────────────────────────
	"neural, network, layer, weight, activation, forward",
	"deep, learning, backprop, gradient, descent, epoch",
	"convolutional, cnn, image, feature, pooling, kernel",
	"recurrent, lstm, sequence, memory, time, gate",
	"transformer, attention, self, encoder, decoder, head",
	"large, language, model, llm, token, prompt, context",
	"embedding, vector, representation, semantic, dense, space",
	"training, epoch, batch, loss, optimize, converge",
	"inference, predict, forward, pass, model, latency",
	"dataset, label, annotate, split, train, validate, test",
	"overfitting, regularize, dropout, weight, decay, early",
	"transfer, learning, pretrain, finetune, domain, adapt",
	"reinforcement, reward, policy, agent, environment, explore",
	"generative, model, sample, diffusion, gan, vae",
	"classification, regression, cluster, predict, class, score",
	"feature, engineer, select, extract, importance, transform",
	"hyperparameter, tune, search, optuna, ray, grid",
	"pipeline, preprocess, transform, fit, evaluate, sklearn",
	"deploy, serve, model, endpoint, inference, triton",
	"explainability, shap, lime, interpret, fairness, audit",

	// ── CRYPTOGRAPHY & SECURITY (298–312) ────────────────────────────────────
	"hash, sha, digest, integrity, checksum, collision",
	"symmetric, aes, key, encrypt, block, cipher, gcm",
	"asymmetric, rsa, public, private, key, pair, ec",
	"signature, sign, verify, authenticity, certificate, chain",
	"zero, knowledge, proof, zkp, privacy, verify, snark",
	"vulnerability, cve, patch, exploit, attack, surface",
	"injection, sql, xss, csrf, owasp, sanitize, escape",
	"penetration, test, red, team, audit, assess, recon",
	"compliance, gdpr, hipaa, sox, pci, regulation, certify",
	"audit, log, trail, access, record, tamper, immutable",
	"privilege, escalation, least, access, minimal, principle",
	"threat, model, surface, risk, mitigate, stride",
	"secret, credential, rotate, vault, manage, scan",
	"zero, trust, verify, explicit, never, trust, network",
	"identity, provider, saml, sso, federation, oidc",

	// ── CONCURRENCY & PARALLELISM (313–327) ──────────────────────────────────
	"thread, mutex, lock, synchronize, critical, section, contention",
	"deadlock, livelock, starvation, priority, inversion, cycle",
	"atomic, operation, compare, swap, spinlock, fence",
	"channel, goroutine, actor, message, pass, mailbox",
	"async, await, promise, future, callback, continuation",
	"semaphore, condition, wait, signal, notify, monitor",
	"worker, pool, task, queue, execute, parallel, throughput",
	"race, condition, thread, safe, data, hazard, access",
	"memory, model, visibility, ordering, barrier, happens, before",
	"immutable, data, share, safe, no, lock, functional",
	"event, loop, single, thread, nonblocking, io, select",
	"coroutine, fiber, cooperative, yield, schedule, green",
	"distributed, consensus, raft, paxos, leader, election",
	"map, reduce, spark, hadoop, parallel, data, partitioned",
	"simd, vectorize, cpu, instruction, parallel, avx",

	// ── ERROR HANDLING & DEBUGGING (328–342) ─────────────────────────────────
	"exception, throw, catch, handle, finally, try, recover",
	"error, return, value, check, propagate, wrap, sentinel",
	"panic, recover, crash, fatal, stack, trace, unwind",
	"stack, overflow, recursion, depth, limit, exhausted",
	"memory, leak, reference, cycle, garbage, collect",
	"null, pointer, dereference, undefined, nil, check",
	"timeout, deadline, cancel, context, expire, signal",
	"retry, backoff, circuit, breaker, resilience, fallback",
	"debug, breakpoint, step, inspect, watch, variable",
	"profiler, hotspot, bottleneck, cpu, flame, graph",
	"heap, dump, analyze, memory, allocation, trace",
	"log, error, warning, trace, info, level, structured",
	"assertion, invariant, contract, precondition, postcondition",
	"sanitize, input, validate, escape, boundary, check",
	"graceful, shutdown, cleanup, signal, terminate, drain",

	// ── FRONTEND & UI (343–357) ───────────────────────────────────────────────
	"component, react, render, state, prop, virtual, dom",
	"dom, html, element, manipulate, browser, query, selector",
	"css, style, responsive, layout, flexbox, grid, breakpoint",
	"accessibility, wcag, aria, screen, reader, keyboard, nav",
	"animation, transition, motion, frame, smooth, easing",
	"form, input, validate, submit, field, control, error",
	"routing, navigation, history, link, page, pushstate",
	"bundle, webpack, vite, build, tree, shake, chunk",
	"state, management, redux, zustand, store, action, reducer",
	"server, side, render, ssr, hydrate, next, static, gen",
	"progressive, web, app, pwa, offline, cache, manifest",
	"theme, dark, light, mode, color, palette, token",
	"typography, font, weight, size, spacing, lineheight",
	"icon, svg, vector, graphic, interface, symbol, sprite",
	"modal, dialog, drawer, notification, toast, overlay",

	// ── MOBILE & EMBEDDED (358–367) ──────────────────────────────────────────
	"android, activity, fragment, lifecycle, intent, view",
	"ios, uikit, swiftui, view, controller, storyboard",
	"react, native, cross, platform, bridge, native, module",
	"embedded, firmware, microcontroller, rtos, interrupt, bare",
	"sensor, accelerometer, gps, bluetooth, wifi, iot, peripheral",
	"battery, power, optimize, background, wake, doze",
	"push, notification, apns, fcm, token, device, register",
	"offline, sync, conflict, local, database, mobile, realm",
	"gesture, touch, swipe, pinch, tap, long, press, drag",
	"camera, microphone, permission, hardware, access, capture",

	// ── OPERATING SYSTEMS (368–377) ──────────────────────────────────────────
	"process, schedule, cpu, context, switch, kernel, preempt",
	"memory, virtual, page, segment, fault, tlb, map",
	"file, system, inode, directory, permission, mount, vfs",
	"interrupt, handler, signal, trap, system, call, ioctl",
	"pipe, socket, ipc, inter, process, communicate, dbus",
	"driver, device, kernel, module, hardware, interface, bus",
	"shell, terminal, command, tty, stdin, stdout, pty",
	"system, call, posix, unix, linux, api, libc",
	"boot, init, daemon, service, startup, systemd, launchd",
	"container, namespace, cgroup, isolation, linux, seccomp",

	// ── VERSION CONTROL & COLLABORATION (378–387) ────────────────────────────
	"branch, feature, develop, release, gitflow, trunk, merge",
	"commit, message, atomic, change, history, amend",
	"merge, conflict, rebase, squash, cherry, pick, resolve",
	"pull, request, review, approve, comment, diff, inline",
	"issue, ticket, backlog, sprint, track, bug, label",
	"fork, upstream, downstream, contribute, open, source, pr",
	"monorepo, workspace, package, dependency, nx, turborepo",
	"tag, release, semantic, version, changelog, note, draft",
	"submodule, subtree, external, dependency, vendor, lock",
	"code, owner, review, responsibility, team, codeowners",

	// ── DOCUMENTATION & COMMUNICATION (388–397) ──────────────────────────────
	"readme, document, explain, guide, overview, project",
	"api, reference, spec, endpoint, parameter, example",
	"comment, inline, explain, why, complex, code, context",
	"diagram, architecture, flow, sequence, class, mermaid",
	"tutorial, example, quickstart, demo, walkthrough, sample",
	"changelog, release, note, breaking, change, migration",
	"glossary, term, definition, concept, vocabulary, jargon",
	"slack, chat, team, communicate, message, channel",
	"meeting, agenda, decision, action, item, async",
	"onboard, new, developer, setup, guide, environment",

	// ── BUSINESS & COMMERCE (398–412) ────────────────────────────────────────
	"product, market, customer, value, need, fit, roadmap",
	"startup, venture, fund, grow, scale, seed, series",
	"revenue, profit, margin, cost, growth, monetize",
	"subscription, saas, mrr, arr, churn, retain, expand",
	"user, acquisition, retention, funnel, conversion, activate",
	"brand, identity, logo, positioning, message, voice",
	"competitor, differentiate, advantage, strategy, moat",
	"supply, chain, vendor, procurement, contract, source",
	"inventory, warehouse, stock, order, fulfillment, pick",
	"payment, invoice, billing, subscription, gateway, stripe",
	"ecommerce, cart, checkout, product, catalog, merchant",
	"analytics, metric, kpi, dashboard, insight, cohort",
	"partnership, integration, ecosystem, platform, channel",
	"enterprise, b2b, saas, contract, negotiate, account",
	"pivot, iteration, feedback, lean, mvp, hypothesis",

	// ── LEGAL & REGULATORY (413–422) ─────────────────────────────────────────
	"contract, agreement, term, condition, sign, execute",
	"intellectual, property, patent, trademark, copyright, trade",
	"privacy, data, protection, gdpr, personal, subject",
	"liability, indemnify, warranty, disclaimer, limit",
	"open, source, license, mit, apache, gpl, copy",
	"compliance, audit, standard, certify, iso, soc2",
	"regulatory, approval, govern, authority, mandate, filing",
	"dispute, arbitration, mediation, resolve, legal, claim",
	"employment, contractor, freelance, hire, nda, non, compete",
	"terms, service, acceptable, use, policy, eula",

	// ── HEALTHCARE & MEDICAL (423–437) ───────────────────────────────────────
	"diagnosis, symptom, condition, clinical, assess, differential",
	"treatment, therapy, medication, dose, prescription, protocol",
	"surgery, procedure, operation, anesthesia, sterile, scrub",
	"laboratory, test, result, specimen, assay, reference",
	"imaging, mri, ct, scan, radiology, ultrasound, x-ray",
	"genomics, dna, rna, sequence, mutation, variant, gene",
	"pharmacology, drug, compound, trial, efficacy, adverse",
	"epidemiology, outbreak, population, incidence, spread, rate",
	"mental, health, depression, anxiety, therapy, psychiatry",
	"nutrition, diet, supplement, vitamin, calorie, micronutrient",
	"vaccine, immune, antibody, protect, response, herd",
	"rehabilitation, recovery, physical, therapy, restore, motor",
	"telemedicine, remote, consult, digital, health, platform",
	"clinical, trial, randomize, control, evidence, placebo",
	"chronic, disease, manage, long, term, care, comorbidity",

	// ── EDUCATION & LEARNING (438–447) ───────────────────────────────────────
	"curriculum, syllabus, lesson, objective, outcome, competency",
	"lecture, seminar, workshop, presentation, teach, explain",
	"assessment, exam, grade, feedback, evaluate, rubric",
	"online, course, mooc, video, self, learn, asynchronous",
	"certificate, degree, credential, accredit, program",
	"research, thesis, dissertation, publish, peer, review",
	"tutor, mentor, coach, guide, support, scaffold",
	"gamification, reward, badge, progress, engage, motivate",
	"adaptive, learning, personalize, pace, level, mastery",
	"language, learn, fluency, practice, immerse, acquire",

	// ── PSYCHOLOGY & COGNITION (448–462) ─────────────────────────────────────
	"attention, focus, distract, mindfulness, aware, selective",
	"memory, recall, forget, encode, retrieve, consolidate",
	"decision, bias, heuristic, cognitive, rational, anchoring",
	"motivation, intrinsic, extrinsic, reward, goal, autonomy",
	"habit, routine, trigger, cue, loop, reward, keystone",
	"emotion, regulate, manage, feel, express, cope, label",
	"personality, trait, introvert, extrovert, openness, agree",
	"creativity, diverge, think, insight, innovation, ideate",
	"stress, burnout, overwhelm, recover, balance, restore",
	"empathy, perspective, understand, relate, compassion",
	"leadership, influence, inspire, vision, direct, servant",
	"team, dynamic, collaborate, trust, norm, psychological",
	"conflict, resolution, negotiation, compromise, mediate",
	"feedback, receive, give, constructive, grow, candor",
	"mindset, growth, fixed, belief, challenge, resilience",

	// ── GEOGRAPHY & PLACE (463–477) ──────────────────────────────────────────
	"city, urban, metropolitan, downtown, suburban, density",
	"country, nation, state, border, sovereign, territory",
	"continent, region, global, international, world, transnational",
	"rural, village, countryside, agricultural, remote, sparse",
	"coast, shoreline, beach, harbor, port, maritime, tidal",
	"river, lake, watershed, basin, freshwater, riparian",
	"latitude, longitude, coordinate, map, projection, datum",
	"infrastructure, road, bridge, tunnel, highway, transit",
	"urban, planning, zone, land, use, density, permit",
	"tourism, destination, travel, visitor, attraction, heritage",
	"cultural, landmark, monument, preserve, history, site",
	"north, south, east, west, cardinal, compass, bearing",
	"elevation, altitude, topography, terrain, contour, dem",
	"geopolitics, border, conflict, territory, claim, sphere",
	"migration, population, settle, urban, rural, diaspora",

	// ── TRANSPORTATION & LOGISTICS (478–487) ─────────────────────────────────
	"supply, chain, logistics, freight, warehouse, fulfillment",
	"shipping, carrier, track, route, delivery, manifest",
	"fleet, vehicle, manage, dispatch, route, optimize, tms",
	"aviation, flight, airport, airline, cargo, faa",
	"rail, train, schedule, cargo, passenger, intermodal",
	"last, mile, delivery, urban, courier, optimize, pod",
	"autonomous, vehicle, self, drive, navigation, lidar",
	"port, container, ship, maritime, terminal, customs",
	"cold, chain, temperature, pharmaceutical, food, frozen",
	"import, export, customs, tariff, duty, incoterms",

	// ── MANUFACTURING & INDUSTRY (488–497) ───────────────────────────────────
	"production, line, assembly, manufacture, quality, throughput",
	"lean, waste, kaizen, continuous, improve, six, sigma",
	"cnc, machining, precision, tolerance, fabricate, toolpath",
	"material, properties, strength, alloy, composite, fatigue",
	"welding, join, metal, fusion, bond, inspect, weld",
	"quality, control, inspect, reject, tolerance, cpk",
	"just, in, time, kanban, inventory, pull, manage",
	"automation, plc, industrial, robot, actuator, scada",
	"maintenance, predictive, preventive, downtime, mtbf",
	"additive, manufacture, 3d, print, prototype, sinter",

	// ── ENERGY & SUSTAINABILITY (498–507) ────────────────────────────────────
	"renewable, solar, wind, hydro, clean, energy, grid",
	"fossil, fuel, coal, oil, gas, emission, combustion",
	"carbon, footprint, offset, neutral, net, zero, scope",
	"battery, storage, charge, discharge, grid, electric, bms",
	"smart, grid, distribute, energy, manage, demand, response",
	"efficiency, consume, save, reduce, optimize, insulate",
	"nuclear, fission, fusion, reactor, waste, coolant",
	"climate, change, global, warming, impact, feedback",
	"sustainability, circular, economy, recycle, reuse, cradle",
	"hydrogen, fuel, cell, green, electrolysis, pem",

	// ── AGRICULTURE & FOOD (508–517) ─────────────────────────────────────────
	"crop, farm, harvest, soil, yield, cultivar, row",
	"irrigation, water, manage, drip, sprinkler, efficient",
	"pest, disease, control, organic, integrated, ipm",
	"livestock, animal, husbandry, feed, breed, welfare",
	"food, safety, hygiene, contamination, haccp, inspect",
	"processing, packaging, preserve, shelf, life, retort",
	"supply, chain, farm, table, trace, origin, provenance",
	"vertical, farm, indoor, hydroponic, controlled, led",
	"genetic, modify, gmo, crop, yield, trait, resistance",
	"fair, trade, organic, certify, label, consumer, premium",

	// ── COMMUNICATION & MEDIA (518–527) ──────────────────────────────────────
	"social, media, platform, engage, content, post, feed",
	"broadcast, television, radio, stream, media, linear",
	"journalism, report, fact, check, bias, source, verify",
	"advertising, campaign, target, impression, click, cpm",
	"public, relation, press, release, reputation, crisis",
	"content, strategy, seo, keyword, organic, search",
	"podcast, audio, episode, subscribe, host, rss",
	"newsletter, email, subscriber, open, rate, deliverability",
	"viral, share, engage, audience, reach, impression, spread",
	"influencer, creator, audience, monetize, brand, deal",

	// ── LINGUISTICS (528–537) ────────────────────────────────────────────────
	"syntax, grammar, parse, sentence, structure, rule",
	"semantics, meaning, word, context, interpret, pragmatics",
	"morphology, word, form, suffix, prefix, root, inflect",
	"phonology, sound, speech, pronunciation, phoneme, prosody",
	"translation, natural, language, multilingual, locale, i18n",
	"sentiment, opinion, positive, negative, neutral, polarity",
	"named, entity, recognition, ner, extract, label, span",
	"tokenize, split, word, piece, subword, bpe, vocab",
	"summarize, abstract, extract, key, point, compress",
	"question, answer, comprehension, context, retrieve, qa",

	// ── NUMBERS & COUNTING (538–547) ─────────────────────────────────────────
	"integer, whole, number, count, discrete, signed",
	"float, decimal, fraction, precision, rounding, ieee",
	"infinity, undefined, overflow, underflow, nan, bound",
	"prime, divisible, factor, modulo, remainder, gcd",
	"percentage, ratio, proportion, fraction, rate, basis",
	"sequence, series, progression, arithmetic, geometric, sum",
	"binary, hexadecimal, octal, base, convert, encode",
	"vector, scalar, tensor, dimension, linear, algebra",
	"complex, imaginary, real, phase, magnitude, polar",
	"random, seed, generate, distribution, uniform, normal",

	// ── SPATIAL & GEOMETRY (548–557) ─────────────────────────────────────────
	"coordinate, point, axis, plane, origin, reference",
	"distance, euclidean, manhattan, cosine, metric, measure",
	"angle, rotation, degree, radian, quaternion, transform",
	"bounding, box, collision, intersect, overlap, aabb",
	"polygon, vertex, edge, face, mesh, triangulate",
	"projection, perspective, orthographic, camera, frustum",
	"scale, translate, rotate, affine, homogeneous, matrix",
	"topology, connected, manifold, surface, genus, euler",
	"path, curve, bezier, spline, nurbs, interpolate",
	"voronoi, delaunay, triangulate, spatial, partition",

	// ── MEASUREMENT & UNITS (558–567) ────────────────────────────────────────
	"time, millisecond, latency, duration, measure, percentile",
	"throughput, request, per, second, rate, capacity, ops",
	"memory, byte, megabyte, gigabyte, usage, resident",
	"cpu, utilization, core, thread, load, average, steal",
	"bandwidth, network, transfer, rate, limit, saturation",
	"temperature, celsius, fahrenheit, kelvin, thermodynamic",
	"weight, gram, kilogram, pound, ounce, mass, force",
	"length, meter, centimeter, inch, foot, distance, measure",
	"power, watt, voltage, current, resistance, ohm, ampere",
	"frequency, hertz, oscillate, cycle, period, wavelength",

	// ── CAUSALITY & INFERENCE (568–577) ──────────────────────────────────────
	"cause, effect, relation, correlation, determine, confound",
	"hypothesis, test, null, reject, accept, evidence, power",
	"infer, deduce, conclude, premise, argument, syllogism",
	"conditional, if, then, else, imply, consequence, branch",
	"feedback, loop, positive, negative, stabilize, amplify",
	"emergent, property, arise, complex, system, nonlinear",
	"bayesian, prior, posterior, update, belief, likelihood",
	"regression, causal, coefficient, predictor, confound",
	"counterfactual, intervention, do, calculus, potential",
	"abduction, best, explanation, inference, reason, diagnose",

	// ── NEGATION & ABSENCE (578–585) ─────────────────────────────────────────
	"empty, null, void, none, absent, missing, zero",
	"never, impossible, forbidden, block, deny, prohibit",
	"remove, delete, destroy, cleanup, garbage, collect",
	"disable, deactivate, stop, halt, pause, suspend",
	"reject, refuse, decline, ignore, skip, discard",
	"deprecated, obsolete, legacy, remove, sunset, old",
	"fail, error, wrong, invalid, corrupt, malformed",
	"incomplete, partial, missing, fragment, broken, stub",

	// ── PROCESS & WORKFLOW (586–595) ─────────────────────────────────────────
	"workflow, step, stage, phase, gate, approve, transition",
	"automation, trigger, schedule, run, job, cron, recurring",
	"orchestration, coordinate, sequence, parallel, task, dag",
	"approval, review, sign, off, checkpoint, stakeholder",
	"notification, alert, escalate, route, assign, sla",
	"template, standard, reuse, consistent, scaffold, boilerplate",
	"backlog, prioritize, groom, sprint, velocity, capacity",
	"deadline, milestone, timeline, schedule, delivery, estimate",
	"delegation, assign, responsible, accountable, raci, owner",
	"iteration, cycle, sprint, review, retrospective, improve",

	// ── STATE & TRANSITION (596–605) ─────────────────────────────────────────
	"active, inactive, enable, disable, status, flag",
	"pending, process, complete, fail, cancel, timeout",
	"open, close, lock, unlock, acquire, release, reentrant",
	"connect, disconnect, online, offline, heartbeat, probe",
	"idle, busy, saturate, queue, wait, ready, blocked",
	"draft, publish, archive, unpublish, status, version",
	"create, read, update, delete, crud, upsert, patch",
	"initialize, reset, bootstrap, teardown, lifecycle, hook",
	"persist, transient, durable, ephemeral, volatile, state",
	"rollout, graduated, progressive, stable, canary, rollback",

	// ── INPUT & OUTPUT (606–613) ──────────────────────────────────────────────
	"read, write, file, stream, buffer, flush, sync",
	"stdin, stdout, stderr, pipe, redirect, dup, fd",
	"keyboard, mouse, input, device, event, handler, raw",
	"display, render, output, screen, terminal, vt100",
	"upload, download, transfer, progress, multipart, chunk",
	"encode, decode, format, parse, serialize, unmarshal",
	"import, export, convert, migrate, transform, etl",
	"print, format, pretty, output, display, sprintf",

	// ── CONDITIONAL & BRANCHING (614–621) ────────────────────────────────────
	"if, else, condition, branch, evaluate, predicate, guard",
	"switch, case, match, pattern, exhaustive, arm, fall",
	"guard, early, return, check, fail, fast, validate",
	"ternary, conditional, expression, inline, short, circuit",
	"flag, boolean, toggle, enable, gate, feature, check",
	"optional, nullable, maybe, nothing, some, value, default",
	"assertion, expect, must, require, ensure, precondition",
	"invariant, always, never, property, maintain, contract",

	// ── LOOP & ITERATION (622–629) ────────────────────────────────────────────
	"loop, iterate, while, until, repeat, range, step",
	"for, each, element, collection, traverse, walk",
	"break, continue, skip, abort, early, exit, next",
	"accumulate, fold, reduce, aggregate, collect, scan",
	"generator, yield, lazy, iterator, produce, pull",
	"recurse, depth, base, case, call, stack, tail",
	"infinite, loop, terminate, convergence, bound, detect",
	"parallel, map, collection, thread, concurrent, pmap",

	// ── SEARCH & DISCOVERY (630–637) ─────────────────────────────────────────
	"search, query, find, locate, match, result, rank",
	"index, inverted, full, text, relevance, tf, idf",
	"facet, filter, refine, narrow, result, bucket, drill",
	"semantic, similarity, vector, nearest, neighbor, ann",
	"autocomplete, suggest, typeahead, prefix, completion",
	"recommendation, collaborative, filter, item, user, matrix",
	"crawl, scrape, extract, index, spider, parse, web",
	"fuzzy, approximate, edit, distance, levenshtein, typo",

	// ── RANKING & PRIORITY (638–645) ─────────────────────────────────────────
	"priority, queue, important, urgent, schedule, preempt",
	"rank, score, relevance, position, order, result, bm25",
	"weight, coefficient, boost, penalty, factor, signal",
	"threshold, cutoff, filter, minimum, maximum, gate",
	"top, k, best, select, candidate, beam, limit",
	"sort, ascending, descending, compare, order, stable",
	"percentile, quantile, distribution, tail, outlier, p99",
	"leaderboard, score, rank, compete, position, ladder",

	// ── GROUPING & AGGREGATION (646–653) ─────────────────────────────────────
	"group, cluster, aggregate, category, segment, bucket",
	"partition, split, divide, distribute, shard, range",
	"merge, combine, join, union, intersection, coalesce",
	"nest, hierarchy, parent, child, tree, level, path",
	"tag, label, classify, annotate, categorize, taxonomy",
	"bucket, bin, histogram, frequency, count, distribute",
	"map, reduce, aggregate, parallel, combiner, shuffle",
	"pivot, reshape, transpose, crosstab, rollup, cube",

	// ── FILTERING & SELECTION (654–661) ──────────────────────────────────────
	"filter, where, condition, predicate, select, exclude",
	"sample, random, subset, representative, stratify, draw",
	"deduplicate, unique, distinct, remove, duplicate, hash",
	"slice, range, window, offset, limit, page, cursor",
	"project, select, column, field, attribute, omit",
	"flatten, normalize, denormalize, reshape, explode",
	"mask, hide, show, visible, reveal, toggle, redact",
	"regex, pattern, match, capture, group, extract, named",

	// ── TRANSFORMATION & MAPPING (662–669) ───────────────────────────────────
	"map, function, apply, transform, each, element, functor",
	"pipeline, compose, chain, sequence, step, dataflow",
	"normalize, standardize, scale, center, whiten, feature",
	"flatten, expand, nest, aggregate, reshape, collect",
	"join, lookup, enrich, augment, combine, hydrate",
	"derive, compute, calculate, formula, expression, eval",
	"cast, coerce, convert, type, promote, widen, narrow",
	"interpolate, extrapolate, estimate, approximate, impute",

	// ── VALIDATION & CONSTRAINT (670–677) ────────────────────────────────────
	"validate, check, verify, constraint, rule, enforce",
	"required, optional, default, boundary, field, schema",
	"type, safe, strict, schema, conform, valid, coerce",
	"sanitize, clean, normalize, escape, input, strip",
	"range, bound, minimum, maximum, clamp, clip, saturate",
	"unique, duplicate, collision, constraint, index, key",
	"format, pattern, match, regex, template, mask",
	"idempotent, retry, safe, consistent, at, least, once",

	// ── EVENTS & NOTIFICATIONS (678–685) ─────────────────────────────────────
	"event, emit, listen, handler, fire, trigger, dispatch",
	"queue, message, broker, consumer, producer, kafka",
	"publish, subscribe, topic, channel, broadcast, fanout",
	"webhook, push, notification, callback, delivery, retry",
	"bus, dispatcher, route, subscriber, decouple, mediator",
	"realtime, websocket, push, live, update, streaming",
	"schedule, cron, job, periodic, interval, recurring, task",
	"saga, choreography, orchestration, distributed, compensate",

	// ── CACHE & MEMORY (686–693) ──────────────────────────────────────────────
	"cache, key, value, expire, ttl, evict, stale",
	"memory, allocate, free, heap, stack, pool, arena",
	"lru, lfu, eviction, policy, least, recently, used",
	"redis, memcache, distributed, shared, cache, cluster",
	"write, through, behind, invalidate, consistency, stale",
	"cdn, edge, cache, static, asset, serve, purge",
	"hot, cold, warm, data, access, pattern, tier",
	"compression, reduce, size, encode, store, decompress",

	// ── LOGGING & MONITORING (694–701) ───────────────────────────────────────
	"log, level, debug, info, warn, error, fatal, trace",
	"structured, log, json, field, context, correlation, id",
	"metric, counter, gauge, histogram, prometheus, scrape",
	"alert, threshold, anomaly, detect, notify, pagerduty",
	"dashboard, visualize, grafana, kibana, panel, query",
	"trace, span, parent, child, context, propagate, baggage",
	"audit, trail, compliance, record, immutable, tamper",
	"retention, policy, rotate, archive, purge, compress, log",

	// ── PARSING & SERIALIZATION (702–711) ────────────────────────────────────
	"json, parse, serialize, key, value, object, array",
	"xml, element, attribute, namespace, xsd, xpath, xslt",
	"yaml, config, indent, anchor, alias, merge, scalar",
	"protobuf, schema, binary, efficient, encode, descriptor",
	"csv, row, column, delimiter, header, field, tsv",
	"lexer, token, grammar, parse, tree, ast, visitor",
	"compiler, ir, optimize, backend, codegen, llvm, emit",
	"interpreter, evaluate, runtime, dynamic, execute, eval",
	"schema, registry, evolve, backward, forward, compatible",
	"binary, encode, varint, length, prefix, wire, fixed",

	// ── COMPRESSION & ENCODING (712–719) ─────────────────────────────────────
	"gzip, compress, deflate, zstd, brotli, reduce, size",
	"base64, encode, decode, binary, text, safe, url",
	"lossy, image, jpeg, quality, artifact, webp, compress",
	"lossless, png, zip, perfect, recover, deflate, compress",
	"codec, encode, decode, format, bitrate, stream, transcode",
	"entropy, huffman, arithmetic, code, optimal, symbol",
	"run, length, encode, repeat, compress, simple, rle",
	"delta, difference, compress, patch, incremental, xdelta",

	// ── GRAPHICS & RENDERING (720–729) ───────────────────────────────────────
	"shader, glsl, hlsl, gpu, vertex, fragment, pipeline",
	"ray, trace, path, bvh, photon, global, illuminate",
	"rasterize, pixel, raster, triangle, scan, convert",
	"texture, uv, map, sample, mipmap, filter, atlas",
	"animation, keyframe, interpolate, bone, rig, skinning",
	"mesh, geometry, vertex, normal, uv, index, buffer",
	"lighting, pbr, material, reflect, diffuse, specular",
	"particle, system, emit, physics, simulate, gpu",
	"post, process, effect, bloom, depth, field, tonemap",
	"webgl, canvas, context, draw, vertex, buffer, vao",

	// ── AUDIO & SIGNAL (730–737) ──────────────────────────────────────────────
	"audio, sample, rate, pcm, channel, stereo, buffer",
	"fourier, transform, frequency, spectrum, fft, dft",
	"filter, low, high, pass, band, equalizer, iir, fir",
	"compress, audio, mp3, aac, opus, vorbis, codec",
	"synthesize, oscillator, wave, envelope, lfo, adsr",
	"speech, recognition, asr, transcribe, model, whisper",
	"noise, cancel, reduce, signal, quality, denoise, snr",
	"midi, music, note, instrument, sequence, event, channel",

	// ── GAME & SIMULATION (738–745) ───────────────────────────────────────────
	"game, loop, update, render, frame, tick, fixed, step",
	"physics, rigid, body, collision, simulate, impulse",
	"entity, component, system, ecs, archetype, query",
	"pathfinding, navigation, mesh, waypoint, astar, flow",
	"level, design, spawn, trigger, zone, event, area",
	"multiplayer, authoritative, lag, compensate, rollback, net",
	"economy, resource, balance, craft, progress, loot",
	"procedural, generate, random, seed, noise, perlin",

	// ── ROBOTICS & CONTROL (746–753) ─────────────────────────────────────────
	"pid, controller, feedback, setpoint, error, integral",
	"kinematics, joint, arm, end, effector, pose, jacobian",
	"sensor, lidar, camera, fuse, perception, imu, depth",
	"ros, node, topic, message, publish, service, robot",
	"motion, plan, obstacle, avoid, trajectory, rrt, prm",
	"actuator, motor, servo, stepper, pwm, torque, control",
	"localize, map, slam, position, estimate, ekf, particle",
	"vision, detect, object, recognize, scene, point, cloud",

	// ── QUANTUM COMPUTING (754–761) ───────────────────────────────────────────
	"qubit, superposition, entangle, measure, collapse, state",
	"gate, hadamard, pauli, cnot, circuit, depth, width",
	"algorithm, shor, grover, quantum, advantage, speedup",
	"noise, error, correct, decohere, fault, tolerant, code",
	"annealing, optimize, energy, minimum, quantum, ising",
	"hybrid, classical, quantum, variational, vqe, qaoa",
	"topological, qubit, majorana, braid, anyonic, surface",
	"quantum, cryptography, distribute, key, secure, bb84",

	// ── ETHICS, FAIRNESS & OPENNESS (762–767) ────────────────────────────────
	"bias, fairness, equity, discriminate, model, audit",
	"privacy, consent, anonymize, protect, differential",
	"transparency, explain, accountable, trust, interpretable",
	"accessibility, include, barrier, universal, design, wcag",
	"environmental, impact, sustainability, carbon, footprint",
	"open, source, community, contribute, share, license",
}

// LandmarkCount is the number of dimensions in a Landmark Lattice vector.
// Must equal len(landmarkBasis) — all 768 dimensions are populated.
const LandmarkCount = 768

// getLandmarkVectors returns the internal integer vectors for each landmark.
// This is used for calculating relative similarity.
func getLandmarkVectors() [][]int64 {
	vectors := make([][]int64, len(landmarkBasis))
	for i, l := range landmarkBasis {
		vectors[i] = embedToLattice(l)
	}
	return vectors
}
